CardPetComponent and Pet Entite
Apple-Developer-Residence-IFCE/LoveMyCalango pull request #1
Opened 2023-05-26 00:53 UTC by Vitor-costa-diniz

Criei a entidade pet e fiz o card de pet que aparece na tela inicial.

2023-05-26 22:15 UTC, IsaiasDimitri commented on loveMyPet/loveMyPet/Preview Content/Preview Assets.xcassets/CardPetComponent.swift
<img width="624" alt="image" src="https://github.com/Apple-Developer-Residence-IFCE/LoveMyCalango/assets/23100444/2d67f2cf-a34a-4e2c-a759-10795cb0202f">

Acho que so essa seta que ficou diferente, mas o resto das medidas estão OK

2023-05-26 23:55 UTC, Vitor-costa-diniz commented on loveMyPet/loveMyPet/Preview Content/Preview Assets.xcassets/CardPetComponent.swift
Esse componente da seta a própria NavigationLink que gera, eu procurei ela no symbols disponíveis do sistema e não achei, ai caso ela gere mesmo eu vou retirar essa seta, se não gerar eu vou colocar como um asset

2023-05-27 00:24 UTC, IsaiasDimitri commented on loveMyPet/loveMyPet/Preview Content/Preview Assets.xcassets/CardPetComponent.swift
Da pra consertar quando tivermos as imagens. Vou aprovar pra gente começar a trabalhar com seu card

2023-05-27 00:24 UTC, IsaiasDimitri approved these changes

2023-05-27 20:43 UTC, ravi2612 approved these changes

2023-05-29 16:30 UTC, MagnoCarta requested changes

2023-05-29 16:30 UTC, MagnoCarta commented on loveMyPet/loveMyPet/Preview Content/Preview Assets.xcassets/CardPetComponent.swift
> +
Pq possui tantos espaços vazios?

2023-05-29 16:30 UTC, MagnoCarta commented on loveMyPet/loveMyPet/Preview Content/Preview Assets.xcassets/CardPetComponent.swift
> +                .padding(.trailing, 5)
será que todos esses números aleatórios aparecendo são legíveis dessa maneira?

2023-05-29 16:30 UTC, MagnoCarta commented on loveMyPet/loveMyPet/Preview Content/Preview Assets.xcassets/CardPetComponent.swift
você pode baixar a seta no Figma

2023-05-29 16:30 UTC, MagnoCarta commented on loveMyPet/loveMyPet/Preview Content/Preview Assets.xcassets/CardPetComponent.swift
mas para facilitar a vida de vocês, direi o nome deste ícone no symbols, "Chevron
"

2023-05-29 16:30 UTC, MagnoCarta commented on loveMyPet/loveMyPet/Preview Content/Preview Assets.xcassets/CardPetComponent.swift
> +        .frame(width: UIScreen.main.bounds.size.width * 0.80,height: 60)
Será que usar UIScreen é uma boa solução?

2023-05-29 22:53 UTC, Vitor-costa-diniz commented on loveMyPet/loveMyPet/Preview Content/Preview Assets.xcassets/CardPetComponent.swift
> +
Ajeitei magno, se puder da uma olhada

2023-05-29 23:34 UTC, MagnoCarta approved these changes

2023-05-29 23:41 UTC, merged