add gender enum
Apple-Developer-Residence-IFCE/LoveMyCalango pull request #11
Opened 2023-05-31 00:19 UTC by rodscesars

2023-05-31 16:59 UTC, MagnoCarta requested changes

2023-05-31 16:59 UTC, MagnoCarta commented on loveMyPet/loveMyPet/Common/Enums/Gender.swift
> +enum Gender: CaseIterable {
você pode assinar String no tipo do Enum e apenas igualar o caso a string, que ele vai direto para o rawvalue , exemplo enum x: String, CaseIterable { case a = "EXEMPLO" }

2023-05-31 21:28 UTC, ravi2612 approved these changes
Resolver conflitos antes de mergear

2023-05-31 23:50 UTC, rodscesars commented on loveMyPet/loveMyPet/Common/Enums/Gender.swift
> +enum Gender: CaseIterable {
Resolvido

2023-05-31 23:55 UTC, IsaiasDimitri approved these changes
lgtm

2023-06-01 21:31 UTC, Vitor-costa-diniz approved these changes

2023-06-01 22:30 UTC, MagnoCarta approved these changes

2023-06-01 22:30 UTC, merged