add pet breed dictionary
Apple-Developer-Residence-IFCE/LoveMyCalango pull request #12
Opened 2023-05-31 00:34 UTC by rodscesars

2023-05-31 17:01 UTC, MagnoCarta approved these changes

2023-05-31 17:01 UTC, MagnoCarta commented on loveMyPet/loveMyPet/Common/Entities/Breed.swift
> +let Breed: Dictionary<Specie, [String]> = [
[Specie : [String]] , Metodo mais usual , mas sem problema deixar assim

2023-05-31 21:26 UTC, ravi2612 requested changes
resolver conflitos da branch

2023-05-31 23:56 UTC, IsaiasDimitri approved these changes

2023-06-01 00:26 UTC, Vitor-costa-diniz approved these changes

2023-06-01 21:34 UTC, ravi2612 approved these changes

2023-06-01 21:36 UTC, merged