Feature/custom navigation
Apple-Developer-Residence-IFCE/LoveMyCalango pull request #14
Opened 2023-05-31 23:44 UTC by IsaiasDimitri

Testing new approach to merge our *.pbxproj files
Adjusting the padding of the Pet's list and apply the navigation correctly.

2023-06-02 00:15 UTC, MagnoCarta requested changes

2023-06-02 00:15 UTC, MagnoCarta commented on .gitattributes
> +*.pbxproj merge=union
Melhor não fazer isso, Aceite que tera que resolver conflitos de pbx kk

2023-06-02 00:15 UTC, MagnoCarta commented on loveMyPet/loveMyPet/Common/Modifiers/HomeModifier.swift
> +    var showingView: AnyView
Type erasure pode dar muita dor de cabeça em views mais complexas, porém darei o braço a torcer, so fiquem espertos se essa é a solução que querem, talvez criar um  tipo genérico que recebe o tipo da view que utiliza customhomenavigation seja uma solução mais apropriada do que AnyView

2023-06-05 23:42 UTC, IsaiasDimitri commented on .gitattributes
> +*.pbxproj merge=union
Vou remover, MB

2023-06-05 23:44 UTC, IsaiasDimitri commented on loveMyPet/loveMyPet/Common/Modifiers/HomeModifier.swift
> +    var showingView: AnyView
Enquanto estava fazendo eu também achei estranho, mas confesso que não achei bons exemplos na internet

2023-06-06 17:08 UTC, MagnoCarta commented on loveMyPet/loveMyPet/Common/Modifiers/HomeModifier.swift
> +    var showingView: AnyView
https://www.kodeco.com/30070603-viewbuilder-tutorial-creating-reusable-swiftui-views

2023-06-06 17:09 UTC, MagnoCarta commented
Após revisão , lembre-se de resolver os conflitos

2023-06-07 22:42 UTC, closed without merging