created PetDetail screen
Apple-Developer-Residence-IFCE/LoveMyCalango pull request #15
Opened 2023-06-01 22:56 UTC by rodscesars

2023-06-01 23:53 UTC, Vitor-costa-diniz approved these changes
So remover os comentarios do código, e quando for iniciar um pet pode usar o .init() para inicializar um pet padão

2023-06-01 23:53 UTC, Vitor-costa-diniz commented on loveMyPet/loveMyPet/Modules/PetDetail/View/PetDetail.swift
> +//    let pet = Pet(image:"Cat", name: "Lua", specie: "Gato", birthDate: Date(), breed: "SRD",  weight: 8.5, isNeutered: true)
Remover comentarios do código

2023-06-02 21:42 UTC, IsaiasDimitri approved these changes
lgtm

2023-06-05 22:58 UTC, MagnoCarta requested changes

2023-06-05 22:58 UTC, MagnoCarta commented on loveMyPet/loveMyPet/Modules/PetDetail/View/PetDetail.swift
> +                HStack {
Note que todos utilizam um padrão muito parecido, talvez haja um jeito de padronizar um componente ou layout com isso  para diminuir repetição de código.

2023-06-06 17:09 UTC, MagnoCarta commented
Após resolver as mudanças , também lembre de resolver os conflitos

2023-06-12 22:08 UTC, ravi2612 approved these changes

2023-06-13 21:33 UTC, MagnoCarta approved these changes

2023-06-13 21:51 UTC, merged