Adding a modifier to apply against our HomeView.
Apple-Developer-Residence-IFCE/LoveMyCalango pull request #2
Opened 2023-05-26 22:01 UTC by IsaiasDimitri

It enables a custom navigation, and reveals a popup that in future will show some register form.

2023-05-27 00:47 UTC, Vitor-costa-diniz approved these changes

2023-05-27 20:46 UTC, ravi2612 commented on loveMyPet/loveMyPet/Common/Modifiers/HomeModifier.swift
> +    }
ajeitar a indentação do código , e excluir linhas brancas desnecessárias , de resto , ficou massa .

2023-05-27 20:47 UTC, ravi2612 approved these changes

2023-05-29 16:34 UTC, MagnoCarta requested changes

2023-05-29 16:34 UTC, MagnoCarta commented on loveMyPet/loveMyPet/Common/Extensions/Extensions.swift
> +    func applyCustomHome(showing showingView: AnyView) -> some View{
falta espaçamento no some View{

2023-05-29 16:34 UTC, MagnoCarta commented on loveMyPet/loveMyPet/Common/Modifiers/HomeModifier.swift
> +    var showingView: AnyView
Pq há um init repetitivo de uma struct? é necessário esse init?

2023-05-29 16:34 UTC, MagnoCarta commented on loveMyPet/loveMyPet/Common/Modifiers/HomeModifier.swift
> +    }
isso

2023-05-29 22:25 UTC, rodscesars approved these changes

2023-05-29 22:26 UTC, IsaiasDimitri commented on loveMyPet/loveMyPet/Common/Extensions/Extensions.swift
> +    func applyCustomHome(showing showingView: AnyView) -> some View{
resolvido!

2023-05-29 22:26 UTC, IsaiasDimitri commented on loveMyPet/loveMyPet/Common/Modifiers/HomeModifier.swift
> +    }
resolvido

2023-05-31 16:56 UTC, MagnoCarta approved these changes

2023-05-31 21:26 UTC, merged