Card Pet Style Component
Apple-Developer-Residence-IFCE/LoveMyCalango pull request #22
Opened 2023-06-12 23:29 UTC by Vitor-costa-diniz

Adicionei as cores para o any e o dark mode, sem precisar usar ternário na view

2023-06-13 21:37 UTC, MagnoCarta requested changes
Conflitos e manager de cores

2023-06-13 21:37 UTC, MagnoCarta commented on loveMyPet/loveMyPet/Preview Content/Preview Assets.xcassets/CardPetComponent.swift
> +                .stroke(Color("BorderCardPet"), lineWidth: 2)
Ainda sinto falta de um manager ou algo para gerir as cores

2023-06-13 22:35 UTC, rodscesars commented on loveMyPet/loveMyPet/Preview Content/Preview Assets.xcassets/CardPetComponent.swift
> +                .stroke(Color("BorderCardPet"), lineWidth: 2)
Resolvido

2023-06-14 00:23 UTC, MagnoCarta approved these changes
Da pra melhorar ainda , mas ja foi uma boa evolução

2023-06-14 00:25 UTC, rodscesars approved these changes

2023-06-14 00:27 UTC, ravi2612 approved these changes

2023-06-14 00:27 UTC, merged