Feature/add task screen
Apple-Developer-Residence-IFCE/LoveMyCalango pull request #36
Opened 2023-07-17 20:07 UTC by rodscesars

Created DateTimeInput component, AddTaskView and AddViewModel

2023-07-18 00:49 UTC, tiago-vargas approved these changes, later dismissed

2023-07-18 00:52 UTC, Vitor-costa-diniz approved these changes, later dismissed

2023-07-19 20:45 UTC, Jwinny requested changes
Projeto não está buildando.
Necessário aprovar o antigo PR e atualizar o código.
--------------------------
<img width="593" alt="Captura de Tela 2023-07-19 às 17 38 49" src="https://github.com/Apple-Developer-Residence-IFCE/LoveMyCalango/assets/56833799/db102299-1ad4-4db3-be2b-ecd4d3ccc688">
----------------
<img width="1066" alt="Captura de Tela 2023-07-19 às 17 44 01" src="https://github.com/Apple-Developer-Residence-IFCE/LoveMyCalango/assets/56833799/ec7a162b-b5bb-4e01-837a-0c23718efb0a">

2023-07-20 00:23 UTC, Jwinny commented
<img width="200" alt="Captura de Tela 2023-07-19 às 21 22 22" src="https://github.com/Apple-Developer-Residence-IFCE/LoveMyCalango/assets/56833799/4e7b382c-5679-453a-833d-c02d072ed470">

Encontrei um problema no preenchimento do Description, pois ele continua infinitamente para o lado e não faz uma quebra de linha.

2023-07-20 00:33 UTC, Jwinny approved these changes
lgtm

2023-07-20 00:34 UTC, Vitor-costa-diniz approved these changes

2023-07-20 00:36 UTC, tiago-vargas approved these changes

2023-07-20 00:36 UTC, merged