Feature/pets home view
Apple-Developer-Residence-IFCE/LoveMyCalango pull request #4
Opened 2023-05-27 22:52 UTC by ravi2612

PetHome maked with Grid And ScrollView , I'm using ForEach to Fetch items in Grid. 
[https://www.notion.so/Tela-de-pets-8895511b3153448bb6827b9455b0863a?pvs=4](url)

https://github.com/Apple-Developer-Residence-IFCE/LoveMyCalango/assets/75507215/391b4d07-6270-46ab-bf0e-a98943dcd6ed

2023-05-29 14:17 UTC, Vitor-costa-diniz approved these changes

2023-05-29 16:46 UTC, MagnoCarta commented
Tem coisa demais nesse PR, aparentemente muitas mudanças nos assets também, essa tarefa era de outra task

2023-05-29 16:59 UTC, MagnoCarta requested changes

2023-05-29 16:59 UTC, MagnoCarta commented on loveMyPet/loveMyPet/Common/Entities/CardPet.swift
> +    init(id: UUID, petName: String, petRace: String, petImage: Image) {
Qual a utilidade desse init?

2023-05-29 16:59 UTC, MagnoCarta commented on loveMyPet/loveMyPet/Common/Enums/Constants.swift
> +        static let Bold = "Poppins-Bold."
Realmente tem esse "."?

2023-05-29 16:59 UTC, MagnoCarta commented on loveMyPet/loveMyPet/Info.plist
Cuidado ao usar infoplist e Entitlements em um mesmo projeto

2023-05-29 16:59 UTC, MagnoCarta commented on loveMyPet/loveMyPet/Modules/Home/Model/HomeModel.swift
> +    private func getPets() {}
vc tem essa função getpets , mas não está gerando os pets nela, e sim na criação da variável pets , pq n deixa aqui?

2023-05-29 16:59 UTC, MagnoCarta commented on loveMyPet/loveMyPet/Modules/Home/View/HomeView.swift
> +                            .foregroundColor(Color("Gray-DBDBDA"))
Será que seria interessante organizar as cores para torna-las mais legíveis ?

2023-05-29 16:59 UTC, MagnoCarta commented on loveMyPet/loveMyPet/Preview Content/Preview Assets.xcassets/CardPetComponent.swift
> +        .frame(width: UIScreen.main.bounds.size.width * 0.80,height: 60)
Será que UIScreen é a melhor solução?

2023-05-29 17:00 UTC, ravi2612 commented on loveMyPet/loveMyPet/Common/Enums/Constants.swift
> +        static let Bold = "Poppins-Bold."
foi erro na copia mesmo do nome da Font

2023-05-29 17:00 UTC, ravi2612 commented on loveMyPet/loveMyPet/Common/Enums/Constants.swift
> +        static let Bold = "Poppins-Bold."
vou tirar o ponto

2023-05-29 17:01 UTC, ravi2612 commented on loveMyPet/loveMyPet/Preview Content/Preview Assets.xcassets/CardPetComponent.swift
> +        .frame(width: UIScreen.main.bounds.size.width * 0.80,height: 60)
o ideal seria linkar o padding .horizontal

2023-05-29 17:22 UTC, ravi2612 commented on loveMyPet/loveMyPet/Preview Content/Preview Assets.xcassets/CardPetComponent.swift
> +        .frame(width: UIScreen.main.bounds.size.width * 0.80,height: 60)
![Captura de Tela 2023-05-29 às 14 22 12](https://github.com/Apple-Developer-Residence-IFCE/LoveMyCalango/assets/75507215/458730c4-b7eb-4770-8b72-dd012dbe6796)
![Captura de Tela 2023-05-29 às 14 22 27](https://github.com/Apple-Developer-Residence-IFCE/LoveMyCalango/assets/75507215/4a1a1ac4-bb32-4027-a5c4-6c108c06bea7)

2023-05-29 17:24 UTC, ravi2612 commented on loveMyPet/loveMyPet/Modules/Home/Model/HomeModel.swift
> +    private func getPets() {}
![Captura de Tela 2023-05-29 às 14 23 48](https://github.com/Apple-Developer-Residence-IFCE/LoveMyCalango/assets/75507215/6b3293c4-7bc8-4ab2-836d-40cbefa5ad35)
@MagnoCarta

2023-05-29 17:26 UTC, ravi2612 commented on loveMyPet/loveMyPet/Common/Entities/CardPet.swift
> +    init(id: UUID, petName: String, petRace: String, petImage: Image) {
para que eu possa dar .init no objeto no getPets

2023-05-29 17:28 UTC, ravi2612 commented on loveMyPet/loveMyPet/Common/Entities/CardPet.swift
> +    init(id: UUID, petName: String, petRace: String, petImage: Image) {
retirado

2023-05-29 17:38 UTC, MagnoCarta commented on loveMyPet/loveMyPet/Modules/Home/Model/HomeModel.swift
> +    private func getPets() {}
Olha que cara bom , perfeito

2023-05-29 17:39 UTC, MagnoCarta approved these changes

2023-05-29 21:38 UTC, IsaiasDimitri approved these changes
lgtm

2023-05-29 21:54 UTC, trastoan commented on loveMyPet/loveMyPet/Modules/Home/View/HomeView.swift
> +                    Grid {
Porquê uma Grid e não uma List?

2023-05-29 22:33 UTC, ravi2612 commented on loveMyPet/loveMyPet/Modules/Home/View/HomeView.swift
> +                    Grid {
A list tem um célula própria , achei mais fácil usar a grid pois ela aceita a minha View sem quebrar o layout como estava ocorrendo com a list. que tem uma área da row ainda para ser configurada .

2023-05-29 22:59 UTC, trastoan commented on loveMyPet/loveMyPet/Modules/Home/View/HomeView.swift
> +                    Grid {
Tu pode usar tuas próprias views na lista, e tu pode sobrescrever o estilo dela com o listStyle botando o .plain se não me engano.

2023-06-01 22:10 UTC, Vitor-costa-diniz requested changes
Resolver conflitos de .DSTore, porque esta adicionando  novamente ao projeto.

2023-06-02 00:22 UTC, closed without merging