Feature/task navigation
Apple-Developer-Residence-IFCE/LoveMyCalango pull request #43
Opened 2023-07-20 12:08 UTC by rodscesars

Integrate AddTaskView to TaskNavigation

2023-07-20 23:00 UTC, tiago-vargas approved these changes

2023-07-20 23:48 UTC, Vitor-costa-diniz approved these changes

2023-07-21 21:37 UTC, Jwinny commented on loveMyPet/loveMyPet/Modules/AddTask/View/AddTaskView.swift
> +    @Environment(\.dismiss) var dissmiss
corrigir `dissmiss` para `dismiss` - retirar o s extra

2023-07-21 21:40 UTC, Jwinny approved these changes
ok

2023-07-21 21:41 UTC, Jwinny requested changes

2023-07-21 21:41 UTC, Jwinny commented on loveMyPet/loveMyPet/Modules/Task/View/TaskView.swift
> +            }.onAppear {
retirar o `onAppear` para não haver requests desnecessárias

2023-07-21 21:44 UTC, rodscesars commented on loveMyPet/loveMyPet/Modules/AddTask/View/AddTaskView.swift
> +    @Environment(\.dismiss) var dissmiss
Fixed

2023-07-21 21:44 UTC, rodscesars commented on loveMyPet/loveMyPet/Modules/Task/View/TaskView.swift
> +            }.onAppear {
Fixed

2023-07-22 00:26 UTC, Jwinny approved these changes
Parece okay. 
Só fazer merge da dev e verificar se não surge nenhum bug.
Nessa branch ainda está com o bug de apagar todos os pets e o de na taskView tá com o espaçamento extra.

2023-07-22 20:12 UTC, merged