Bugfix/image
Apple-Developer-Residence-IFCE/LoveMyCalango pull request #44
Opened 2023-07-20 22:23 UTC by Jwinny

<img width="281" alt="Captura de Tela 2023-07-20 às 19 22 56" src="https://github.com/Apple-Developer-Residence-IFCE/LoveMyCalango/assets/56833799/f183f8b6-d920-4c85-9449-e851efdc052a">

Consertado o bug visual da TabBar

2023-07-20 22:50 UTC, tiago-vargas approved these changes

2023-07-20 22:51 UTC, rodscesars approved these changes

2023-07-20 22:52 UTC, Vitor-costa-diniz approved these changes

2023-07-21 00:33 UTC, Vitor-costa-diniz requested changes
Quebrou a dev cara, cade a noção ????

2023-07-21 00:34 UTC, closed without merging

2023-07-21 00:35 UTC, Vitor-costa-diniz commented
Pesso perdão aos integrantes